receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      # http:
      #   endpoint: 0.0.0.0:4318
      #   cors:
      #     allowed_origins: "http://*"
processors:
  batch:
  # redaction:
  #   # Flag to allow all span attribute keys. Setting this to true disables the
  #   # allowed_keys list. The list of blocked_values is applied regardless. If
  #   # you just want to block values, set this to true.
  #   allow_all_keys: false
  #   # Allowlist for span attribute keys. The list is designed to fail closed.
  #   # If allowed_keys is empty, no span attributes are allowed and all span
  #   # attributes are removed. To allow all keys, set allow_all_keys to true.
  #   # To allow the span attributes you know are good, add them to the list.
  #   allowed_keys:
  #     - description
  #     - group
  #     - id
  #     - name
  #   # BlockedValues is a list of regular expressions for blocking values of
  #   # allowed span attributes. Values that match are masked
  #   blocked_values:
  #     - "4[0-9]{12}(?:[0-9]{3})?" ## Visa credit card number
  #     - "(5[1-5][0-9]{14})"       ## MasterCard number
  #   # Summary controls the verbosity level of the diagnostic attributes that
  #   # the processor adds to the spans when it redacts or masks other
  #   # attributes. In some contexts a list of redacted attributes leaks
  #   # information, while it is valuable when integrating and testing a new
  #   # configuration. Possible values are `debug`, `info`, and `silent`.
  #   summary: debug

exporters:
  # Data sources: traces, metrics, logs
  file:
    path: /logs/collector-logs.json
#   logging:
#     loglevel: debug
  otlp/traces:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
      "x-honeycomb-dataset": "${HONEYCOMB_DATASET}"
#   otlp/logs:
#     endpoint: "api.honeycomb.io:443"
#     headers:
#       "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
#       "x-honeycomb-dataset": "sasha-test"
#   file:
#     path: /logs/otelLogs.json

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/traces]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
